####
# General Config
####

# The version number being built. Should match version in CMake/at runtime.
# This is the ACTUAL version number used when uploading to GitHub Releases.
environment:
  APP_VERSION: 0.0.7

# Appveyor version number - used only for the unique build version required by Appveyor.
version: $(APP_VERSION)-{build}

# The goal is to build and deploy occasional release milestones to GitHub.
# Rather than building every commit to master, we'll only build when merging into release branch.
branches:
  only:
    - release

# Do not build tags.
skip_tags: true

# I think this is a limitation of the free plan anyway!
max_jobs: 1

####
# Environment Config
####

# Build for Windows and Mac.
image: 
  - macos
  - Visual Studio 2019

# Init script runs before cloning the repo.
#init:
#  - echo Init

# Install scripts run after cloning completes.
#install:
#  - echo Install

####
# Build Config
####

# Can be one of (Debug, Release, RelWithDebInfo, MinSizeRel) - from CMake.
configuration: RelWithDebInfo

# Scripts to run before build.
before_build:
  # For Mac: generate Xcode project.
  - sh: cmake -B build_appveyor -G Xcode .

  # For Windows: generte VS project
  - cmd: cmake -B build_appveyor -G "Visual Studio 16 2019" -A Win32
  
  # Alternate approach that uses Ninja - maybe faster?
  # Execute the cmake command that VS exectutes (pulled from VS CMake output log).
  #- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  #- cmd: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="%CONFIGURATION%" -DCMAKE_C_COMPILER:FILEPATH="cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="cl.exe" -DCMAKE_MAKE_PROGRAM="ninja.exe" .

build_script:
  - sh: cmake --build build_appveyor --target deploy --config ${CONFIGURATION}
  - cmd: cmake --build build_appveyor --target deploy --config %CONFIGURATION%

# Scripts to run after build.
#after_build:
#  - echo After Build

####
# Tests Config
####

# Scripts to run before tests.
before_test:
  - sh: cmake --build build_appveyor --target tests --config ${CONFIGURATION}
  - cmd: cmake --build build_appveyor --target tests --config %CONFIGURATION%

# Scripts to run for tests.
test_script:
  - sh: ./build_appveyor/Tests/${CONFIGURATION}/tests
  - cmd: build_appveyor\Tests\%CONFIGURATION%\tests.exe

# Scripts to run after tests.
#after_test:
#  - echo After Tests

####
# Artifact Config
####

# Build scripts will leave ready-to-deploy app in "Bin" folder 
artifacts:
  - path: Bin/$(CONFIGURATION)/*.zip
    name: Game

####
# Deployment Config
####

# Scripts to run before deployment.
#before_deploy:
#  - echo Before Deploy

# Deploy to GitHub Releases
deploy:
  - provider: GitHub
    artifact: Game
    release: 'v$(APP_VERSION)'
    description: 'GEngine version $(APP_VERSION) for Mac and Windows'
    force_update: true # allows multiple jobs to upload artifacts to same GitHub release
    auth_token:
      secure: +FLIpiKwFVgZmhUkmcDZK9P727eAjboXu+dfZ5G8xnNETVhPbRkIV57ckpcSr6Rz

# Scripts to run after deployment.
#after_deploy:
#  - echo After Deploy

####
# Handlers
####

# Scripts to run on successful build completion.
on_success:
  - echo Success

# Scripts to run on build failure.
on_failure:
  - echo Failure

# Scripts to run on build finish (success or failure).
on_finish:
  - echo Finish

####
# Notifications
####

# A way to send a notif (email, Slack, etc) when a build finishes.
# Just to test it out, I'll send myself an email on build status change.
notifications:
  - provider: Email
    to:
      - kromenak@gmail.com
    # Exclude custom subject/message to use the default ones.
    #subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
    #message: "{{message}}, {{commitId}}"
    on_build_failure: true
    on_build_status_changed: true
